name: Build and Push Container

on:
  push:
    branches:
      - main # When "main" is pushed
  schedule:
    - cron: '0 3 * * *' # Everyday at 3AM

env:
  IMAGE_NAME: rslashdisneyvacation/moderationbot

jobs:
  main:
    name: Build and Push container
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
